/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as RentalsRouteImport } from './routes/rentals'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as ExplorePropertyListingIdRouteImport } from './routes/explore.property.$listingId'
import { Route as RentalsPropertyListingIdRouteImport } from './routes/rentals.property.$listingId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const RentalsRoute = RentalsRouteImport.update({
  id: '/rentals',
  path: '/rentals',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorePropertyListingIdRoute =
  ExplorePropertyListingIdRouteImport.update({
    id: '/property/$listingId',
    path: '/property/$listingId',
    getParentRoute: () => ExploreRoute,
  } as any)
const RentalsPropertyListingIdRoute =
  RentalsPropertyListingIdRouteImport.update({
    id: '/property/$listingId',
    path: '/property/$listingId',
    getParentRoute: () => RentalsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/rentals': typeof RentalsRouteWithChildren
  '/saved': typeof SavedRoute
  '/stats': typeof StatsRoute
  '/explore/property/$listingId': typeof ExplorePropertyListingIdRoute
  '/rentals/property/$listingId': typeof RentalsPropertyListingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/rentals': typeof RentalsRouteWithChildren
  '/saved': typeof SavedRoute
  '/stats': typeof StatsRoute
  '/explore/property/$listingId': typeof ExplorePropertyListingIdRoute
  '/rentals/property/$listingId': typeof RentalsPropertyListingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/explore': typeof ExploreRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/rentals': typeof RentalsRouteWithChildren
  '/saved': typeof SavedRoute
  '/stats': typeof StatsRoute
  '/explore/property/$listingId': typeof ExplorePropertyListingIdRoute
  '/rentals/property/$listingId': typeof RentalsPropertyListingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/explore'
    | '/favorites'
    | '/rentals'
    | '/saved'
    | '/stats'
    | '/explore/property/$listingId'
    | '/rentals/property/$listingId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/explore'
    | '/favorites'
    | '/rentals'
    | '/saved'
    | '/stats'
    | '/explore/property/$listingId'
    | '/rentals/property/$listingId'
  id:
    | '__root__'
    | '/'
    | '/explore'
    | '/favorites'
    | '/rentals'
    | '/saved'
    | '/stats'
    | '/explore/property/$listingId'
    | '/rentals/property/$listingId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExploreRoute: typeof ExploreRouteWithChildren
  FavoritesRoute: typeof FavoritesRoute
  RentalsRoute: typeof RentalsRouteWithChildren
  SavedRoute: typeof SavedRoute
  StatsRoute: typeof StatsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rentals': {
      id: '/rentals'
      path: '/rentals'
      fullPath: '/rentals'
      preLoaderRoute: typeof RentalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/property/$listingId': {
      id: '/explore/property/$listingId'
      path: '/property/$listingId'
      fullPath: '/explore/property/$listingId'
      preLoaderRoute: typeof ExplorePropertyListingIdRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/rentals/property/$listingId': {
      id: '/rentals/property/$listingId'
      path: '/property/$listingId'
      fullPath: '/rentals/property/$listingId'
      preLoaderRoute: typeof RentalsPropertyListingIdRouteImport
      parentRoute: typeof RentalsRoute
    }
  }
}

interface ExploreRouteChildren {
  ExplorePropertyListingIdRoute: typeof ExplorePropertyListingIdRoute
}

const ExploreRouteChildren: ExploreRouteChildren = {
  ExplorePropertyListingIdRoute: ExplorePropertyListingIdRoute,
}

const ExploreRouteWithChildren =
  ExploreRoute._addFileChildren(ExploreRouteChildren)

interface RentalsRouteChildren {
  RentalsPropertyListingIdRoute: typeof RentalsPropertyListingIdRoute
}

const RentalsRouteChildren: RentalsRouteChildren = {
  RentalsPropertyListingIdRoute: RentalsPropertyListingIdRoute,
}

const RentalsRouteWithChildren =
  RentalsRoute._addFileChildren(RentalsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExploreRoute: ExploreRouteWithChildren,
  FavoritesRoute: FavoritesRoute,
  RentalsRoute: RentalsRouteWithChildren,
  SavedRoute: SavedRoute,
  StatsRoute: StatsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
