/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as ExplorePropertyListingIdRouteImport } from './routes/explore.property.$listingId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorePropertyListingIdRoute =
  ExplorePropertyListingIdRouteImport.update({
    id: '/property/$listingId',
    path: '/property/$listingId',
    getParentRoute: () => ExploreRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/saved': typeof SavedRoute
  '/stats': typeof StatsRoute
  '/explore/property/$listingId': typeof ExplorePropertyListingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/saved': typeof SavedRoute
  '/stats': typeof StatsRoute
  '/explore/property/$listingId': typeof ExplorePropertyListingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/explore': typeof ExploreRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/saved': typeof SavedRoute
  '/stats': typeof StatsRoute
  '/explore/property/$listingId': typeof ExplorePropertyListingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/explore'
    | '/favorites'
    | '/saved'
    | '/stats'
    | '/explore/property/$listingId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/explore'
    | '/favorites'
    | '/saved'
    | '/stats'
    | '/explore/property/$listingId'
  id:
    | '__root__'
    | '/'
    | '/explore'
    | '/favorites'
    | '/saved'
    | '/stats'
    | '/explore/property/$listingId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExploreRoute: typeof ExploreRouteWithChildren
  FavoritesRoute: typeof FavoritesRoute
  SavedRoute: typeof SavedRoute
  StatsRoute: typeof StatsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/property/$listingId': {
      id: '/explore/property/$listingId'
      path: '/property/$listingId'
      fullPath: '/explore/property/$listingId'
      preLoaderRoute: typeof ExplorePropertyListingIdRouteImport
      parentRoute: typeof ExploreRoute
    }
  }
}

interface ExploreRouteChildren {
  ExplorePropertyListingIdRoute: typeof ExplorePropertyListingIdRoute
}

const ExploreRouteChildren: ExploreRouteChildren = {
  ExplorePropertyListingIdRoute: ExplorePropertyListingIdRoute,
}

const ExploreRouteWithChildren =
  ExploreRoute._addFileChildren(ExploreRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExploreRoute: ExploreRouteWithChildren,
  FavoritesRoute: FavoritesRoute,
  SavedRoute: SavedRoute,
  StatsRoute: StatsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
